### ISSUE TITLE
release buildだと通信できない

### ISSUE THREAD

**Issue by darlington95** [darlington95/reading_miria#1]
debug buildでは問題なく通信してタイムラインを表示しますが、release buildだと通信しません。  
Wiresharkで観測すると1バケットも出ていない感じです。  
私は、Appleのアプリのビルドは初心者なので、基本的な要件が漏れているのかもしれません。  
私が試みた手順は、Wiki "[IntelのMacでビルドする](https://github.com/darlington95/reading_miria/wiki/Intel%E3%81%AEMac%E3%81%A7%E3%83%93%E3%83%AB%E3%83%89%E3%81%99%E3%82%8B)" に書いたとおりです。

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed host lookup: 'misskey.io' (OS Error: nodename nor servname provided, or not known, errno = 8)
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1914)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:299)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:77)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2483)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2926)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2931)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2786)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2623)
#10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021)
#11     WebSocket.connect (dart:_http/websocket.dart:320)
#12     new IOWebSocketChannel.connect (package:web_socket_channel/io.dart:81)
#13     StreamingService.webSocketChannel (package:misskey_dart/src/services/streaming_service.dart:38)
#14     SocketController.webSocketChannel (package:misskey_dart/src/services/socket_controller.dart:16)
#15     SocketController.connect (package:misskey_dart/src/services/socket_controller.dart:53)
#16     StreamingService.connect (package:misskey_dart/src/services/streaming_service.dart:170)
#17     Misskey.homeTimelineStream (package:misskey_dart/src/misskey_dart_base.dart:164)
#18     HomeTimeLineRepository.createSocketController (package:miria/repository/home_time_line_repository.dart:29)
#19     SocketTimelineRepository.startTimeLine (package:miria/repository/socket_timeline_repository.dart:103)
<asynchronous suspension>

2024-03-29 20:05:40.209 miria[63432:6431370] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
```

**Comment by darlington95** [comment]
検索すると、https://stackoverflow.com/questions/77283578/sonoma-and-nsapplicationdelegate-applicationsupportssecurerestorablestate がそれっぽいのですが、具体的に何をしたらいいのかな。理解が追い付いていない感じです。

当面、そのままデバッグビルドで使います。私が外にリリースする予定はないので。

**Comment by darlington95** [comment]
## Misskeyで情報をいただきまして、通信できるようになりました。

XcodeでApp Sandbox (Release)のNetworkが無効になっていたのが原因でした。  
miriaはクライアント機能だけなのでOutgoing  Connectionsにチェックを入れてリリースビルドしたところ、めでたく通信できました!!   
4steriskさんありがとうございます。
![スクリーンショット 2024-03-30 0 25 51](https://github.com/darlington95/reading_miria/assets/8266969/b348efdd-0ab8-4a19-b479-ffc7ac8f2ab8)

![スクリーンショット 2024-03-30 0 57 12](https://github.com/darlington95/reading_miria/assets/8266969/97888f23-27c8-48ba-b995-dffe17d4e5ee)
